image: node
stages:
  - test
  - package
  - deploy

cache:
 paths:
  - ./website/build

before_script:
  - whoami
  - pwd

#CHECA SE ALGUM LINK NO SITE ESTÁ QUEBRADO ANTES DE BUILDAR
test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker wait-on
  script:
    - cd website
    - npm install && npm run start &
    - wait-on http://localhost:3000
    - blc --recursive --exclude-external http://localhost:3000
  
package site:
  stage: package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths: 
      - ./website/build/missaodevops
    when: always
    expire_in: 1 week
  script:
    - ls -ltra
    - pwd
    - whoami
    - npm --version
    - cd website
    - npm install
    - npm run build

deploy to staging:
  stage: deploy
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/missaodevops --domain http://eullercristian.surge.sh/
  after_script:
    - whoami
  environment:
    name: staging
    url: http://eullercristian.surge.sh/
  only:
    - develop