image: node
stages:
  - test
  - package
  - deploy

before_script:
  - whoami
  - pwd

#CHECA SE ALGUM LINK NO SITE ESTÁ QUEBRADO ANTES DE BUILDAR
# test site:
#   stage: test
#   before_script:
#     - npm install -g broken-link-checker wait-on
#   script:
#     - cd website
#     - npm install && npm run start &
#     - wait-on http://localhost:3000
#     #  valida a integridade de todas as urls e paths de imagens
#     #- blc --recursive --exclude-external http://localhost:3000

# vulnerabilidades check:
#   stage: test
#   script:
#     - cd website 
#     - npm install
#     - npm run scan

package site:
  stage: package
  cache:
    key: site-package
    policy: push
    paths:
    - ./website/build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths: 
      - ./website/build/missaodevops
    when: always
    expire_in: 1 week
  script:
    - ls -ltra
    - pwd
    - whoami
    - npm --version
    - cd website
    - npm install
    - npm run build

deploy to staging:
  stage: deploy
  variables:
    CNAME: staging.eullercristian.surge.sh
    GIT_STRATEGY: "none"
  cache:
    key: site-package
    policy: pull
    paths:
    - ./website/build  
  before_script:
    - npm install -g surge@^0.20.1
  script:
    - surge --project ./website/build/missaodevops --domain staging.eullercristian.surge.sh
  after_script:
    - whoami
  environment:
    name: staging
    url: http://staging.eullercristian.surge.sh
  only:
    - develop

deploy to release:
  stage: deploy
  variables:
    CNAME: $CI_COMMIT_REF_SLUG.eullercristian.surge.sh
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
    paths:
    - ./website/build  
  before_script:
    - npm install -g surge@^0.20.1
  script:
    - surge --project ./website/build/missaodevops --domain ${CNAME}
  after_script:
    - whoami
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CNAME}  
    on_stop: turnoff 
  only:
    - /^release-.*$/

turnoff:
  stage: deploy
  variables:
    CNAME: $CI_COMMIT_REF_SLUG-eullercristian.surge.sh
    GIT_STRATEGY: none
  before_script:
    - npm install -g surge@^0.20.1
  script:
    - surge teardown ${CNAME}
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: ${CNAME}
    action: stop    
  only:
    - /^release-.*$/
  
  
deploy to production:
  stage: deploy
  variables:
    CNAME: eullercristian.surge.sh
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
    paths:
    - ./website/build  
  before_script:
    - npm install -g surge@^0.20.1
  script:
    - surge --project ./website/build/missaodevops --domain ${CNAME}
  after_script:
    - whoami
  environment:
    name: production
    url: http://${CNAME}
  only:
    - master