image: node
stages:
  - test
  - package
  - deploy

before_script:
  - whoami
  - pwd

#CHECA SE ALGUM LINK NO SITE ESTÁ QUEBRADO ANTES DE BUILDAR
test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker wait-on
  script:
    - cd website
    - npm install && npm run start &
    - wait-on http://localhost:3000
    #- blc --recursive --exclude-external http://localhost:3000

vulnerabilidades check:
  stage: test
  script:
    - cd website && npm install -g snyk && snyk auth
    - snyk test

package site:
  stage: package
  cache:
    key: site-package
    policy: push
    paths:
    - ./website/build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths: 
      - ./website/build/missaodevops
    when: always
    expire_in: 1 week
  script:
    - ls -ltra
    - pwd
    - whoami
    - npm --version
    - cd website
    - npm install
    - npm run build

deploy to staging:
  stage: deploy
  cache:
    key: site-package
    policy: pull
    paths:
    - ./website/build  
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/missaodevops --domain http://eullercristian.surge.sh/
  after_script:
    - whoami
  environment:
    name: staging
    url: http://eullercristian.surge.sh/
  only:
    - develop