image: node
stages:
  - build
  - test
  - deploy
build site:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths: 
      - ./builds/devopsecdr/gitlabci/website
    when: always
    expire_in: 1 week
  script:
    - ls -ltra
    - pwd
    - whoami
    - npm --version
    - cd website
    - npm install
    - npm run build