image: node
stages:
  - build
  - test
  - deploy

 cache:
 paths:
  - ./website/build

 build site:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths: 
      - ./website/build/missaodevops
    when: always
    expire_in: 1 week
  script:
    - ls -ltra
    - pwd
    - whoami
    - npm --version
    - cd website
    - npm install
    - npm run build
deploy website:
  stage: deploy
  scripts:
    - npm install -g surge
    - surge --project ./website/build/missaodevops --domain http://eullercristian.surge.sh

