image: node
stages:
  - build
  - test
  - deploy
build site:
  stage: build
  artifacts:
    paths:
    - ./website/build/docusaurus
    expire_in: 1 week
  script:
    - ls -ltra
    - pwd
    - whoami
    - npm --version
    - cd website
    - npm install
    - npm run build