image: node
stages:
  - build
  - test
  - deploy

cache:
 paths:
  - ./website/build

before_script:
  - whoami
  - pwd

build site:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths: 
      - ./website/build/missaodevops
    when: always
    expire_in: 1 week
  script:
    - ls -ltra
    - pwd
    - whoami
    - npm --version
    - cd website
    - npm install
    - npm run build

deploy website:
  stage: deploy
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/missaodevops --domain http://eullercristian.surge.sh/
  after_script:
    - whoami
  environment:
    name: staging
    url: http://eullercristian.surge.sh/
  only:
    - develop